# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик.
  # Это контейнер БД
  db:
    # Из какого образа запускается контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собрать образ для этого контейнера:
      build: ./backend/
      env_file: .env
      # Какие контейнеры нужно запустить до старта этого контейнера:
      depends_on:
        - db
  # Имя третьего контейнера. Этот контейнер с фроотендом
  frontend:
    env_file: .env
    build: ./frontend/
